kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
- name: mysql-pass
  literals:
  - password=123456
resources:
  - namespace.yaml
  - mysql-deployment.yaml
  - wordpress-deployment.yaml
