kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
  labels:
    password: wordpress
secretGenerator:
- name: mysql-pass
  literals:
  - password=wordpress
resources:
  - namespace.yaml
  - mysql-deployment.yaml
  - wordpress-deployment.yaml
